// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcCSharp6.Models;

namespace MvcCSharp6.Migrations
{
    [DbContext(typeof(MovieDataContext))]
    [Migration("20230221203800_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MvcCSharp6.Models.CategoryModel", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            categoryName = "comedy"
                        },
                        new
                        {
                            categoryId = 2,
                            categoryName = "drama"
                        },
                        new
                        {
                            categoryId = 3,
                            categoryName = "action/adventure"
                        },
                        new
                        {
                            categoryId = 4,
                            categoryName = "romance"
                        },
                        new
                        {
                            categoryId = 5,
                            categoryName = "historical fiction"
                        },
                        new
                        {
                            categoryId = 6,
                            categoryName = "history"
                        },
                        new
                        {
                            categoryId = 7,
                            categoryName = "documentary"
                        });
                });

            modelBuilder.Entity("MvcCSharp6.Models.MovieModel", b =>
                {
                    b.Property<int>("movieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("movieId");

                    b.HasIndex("categoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            movieId = 1,
                            categoryId = 1,
                            director = "John Lasseter",
                            edited = false,
                            notes = "super emotional",
                            rating = "G",
                            title = "Cars 2",
                            year = (ushort)2011
                        },
                        new
                        {
                            movieId = 2,
                            categoryId = 2,
                            director = "Tom McGrath",
                            edited = false,
                            notes = "greatest movie ever made",
                            rating = "PG",
                            title = "Megamind",
                            year = (ushort)2010
                        },
                        new
                        {
                            movieId = 3,
                            categoryId = 5,
                            director = "Steven Spielberg",
                            edited = false,
                            notes = "wow",
                            rating = "R",
                            title = "Saving Private Ryan",
                            year = (ushort)1998
                        });
                });

            modelBuilder.Entity("MvcCSharp6.Models.MovieModel", b =>
                {
                    b.HasOne("MvcCSharp6.Models.CategoryModel", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
